#!/bin/bash

#SBATCH --job-name test
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --time=00:10:0
#SBATCH --output test.out
#SBATCH --account=cosc029104

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
OMP_DISPLAY_ENV=true
# Run the executable
python -u test.py
